replicaCount: 1

image:
  name: user-service
  repository: user-service
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  httpPort: 8080
  grpcPort: 50051

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: DB_DSN
    value: root:VA2ykQe2zK@tcp(db-mysql.default.svc.cluster.local:3306)/user-service?charset=utf8mb4&parseTime=True&loc=Local
    
