replicaCount: 1

image:
  repository: user-service
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
labels:
  app.kubernetes.io/name: user-service
  app.kubernetes.io/instance: RELEASE-NAME
  app.kubernetes.io/managed-by: Helm
  app.kubernetes.io/version: "1.16.0"
  app.kubernetes.io/component: user-service
  app.kubernetes.io/part-of: user-service
  app.kubernetes.io/created-by: Helm
  app.kubernetes.io/chart: user-service-0.1.0
  app.kubernetes.io/heritage: Helm

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  httpPort: 8080
  grpcPort: 50051

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: DB_DSN
    value: root:VA2ykQe2zK@tcp(db-mysql.default.svc.cluster.local:3306)/user-service?charset=utf8mb4&parseTime=True&loc=Local
    
